name: quizflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flip_card: ^0.7.0
  archive: ^3.4.6
  sqflite: ^2.3.0
  file_picker: ^6.0.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  provider: ^6.1.1
  googleapis: ^11.4.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  expansion_tile_card: ^3.0.0
  animate_do: ^3.1.2
  langchain: ^0.2.1
  langchain_openai: ^0.2.0+1
  pinecone: ^0.7.2
  time: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.0

dependency_overrides:
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets: 
    - assets/sounds/pass.mp3
    - assets/sounds/pass2.mp3
    - assets/sounds/pass2.wav
    - assets/sounds/pass3.wav
    - assets/images/img.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo2.ttf
