// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9i2rhc5qQhaS11w1tzyJqlKsYsGUzcEA',
    appId: '1:172740453920:android:9dc1a9c66d3f8a009c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    storageBucket: 'quizflow-2a62d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7uy--2gZTGXr-7MYwm1un0ik9OQFvU1c',
    appId: '1:172740453920:ios:068964a10fe595569c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    storageBucket: 'quizflow-2a62d.appspot.com',
    androidClientId: '172740453920-lshmcaif76p5h3ka8l0r4pvphkkftor5.apps.googleusercontent.com',
    iosClientId: '172740453920-91o7mfsacmftkmmf3avaakqeijmshpc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizflow',
  );
}
