// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1at7pE5BgicxJT-EzlAHqXT3RmdJgq8',
    appId: '1:172740453920:web:0e491929d2a22e5d9c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    authDomain: 'quizflow-2a62d.firebaseapp.com',
    storageBucket: 'quizflow-2a62d.appspot.com',
    measurementId: 'G-6KK6SZFSPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahIWKxPa28jtw3536ZBQLS3rE8O4dYsA',
    appId: '1:172740453920:android:9dc1a9c66d3f8a009c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    storageBucket: 'quizflow-2a62d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQglwdE8jgzQN1IN_et-nSrFYeP1BoCkw',
    appId: '1:172740453920:ios:068964a10fe595569c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    storageBucket: 'quizflow-2a62d.appspot.com',
    iosBundleId: 'com.example.quizflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQglwdE8jgzQN1IN_et-nSrFYeP1BoCkw',
    appId: '1:172740453920:ios:2c2925016df0b3e59c3e45',
    messagingSenderId: '172740453920',
    projectId: 'quizflow-2a62d',
    storageBucket: 'quizflow-2a62d.appspot.com',
    iosBundleId: 'com.example.quizflow.RunnerTests',
  );
}
